#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
while :; do 
    if [[ -d "$DIR/scada.js" ]]; then 
        r=$DIR
        break
    fi
    DIR=$(dirname $DIR)
    if [[ "$DIR" = "/" ]]; then
        echo "Scada.js root can not be found."
        exit 2
    fi
done
source $r/scada.js/tools/node-path.sh
source $r/scada.js/tools/debug-ls/debug-ls
